### PR TITLE
Singular module refactored to test dropdowns with bootstrap

### PR DESCRIPTION
**Pull request by KeenanRileyFaulkner**

### CODE REVIEW

**Comment by jgoeders** [comment]
@philipbl Here is a sample of how we could do the expanding text.  As you can see, we unfortunately we end up having to do a lot of the HTML formatting for our text.  Do you know a work-around at all?  Can we call some jekyll function inside the HTML to automatically format markdown into HTML here?  ...does that make senese?

**Comment by KeenanRileyFaulkner** [comment]
@jgoeders @philipbl the main issue I was having is weird line breaks unless everything was in HTML syntax and wrapped in a p tag if it contained code or em or strong tags. I don't know how to overcome that.

**Comment by jgoeders** [comment]
@KeenanRileyFaulkner Does this work? https://stackoverflow.com/a/23384161/609215

Essentially markdown within HTML within markdown?

**Comment by KeenanRileyFaulkner** [comment]
I'll give it a shot when I get in tomorrow

**Comment by jgoeders** [comment]
Also, personally I like it with just a link instead of a big button:

image

I did this by just removing the class="btn ..." and shrinking the font a bit.

**Comment by jgoeders** [comment]
Maybe with a plus icon in the text?

```
+ More Details
```

**Comment by KeenanRileyFaulkner** [comment]
Looks like the markdown="1" attribute allows me to get rid of the code, strong and em tags, but not the p tags or anything else (such as ul and li tags or the significant amount of bootstrap boilerplate). @jgoeders

**Comment by jgoeders** [comment]
Could you update this branch with the markdown tag so we can try it out and see what else we can do?

**Comment by KeenanRileyFaulkner** [comment]
Yeah, give me like 5 mins. I've been messing with a ul tag trying to get it back to markdown but it's not working at all, so I'm switching back to HTML syntax on that part. Then I'll push

**Comment by KeenanRileyFaulkner** [comment]
Done @jgoeders

**Comment by jgoeders** [comment]
@KeenanRileyFaulkner OK, I found a much better way to do this.  Check out: https://github.com/byu-cpe/y-badge/pull/18/files

**Comment by jgoeders** [comment]
@KeenanRileyFaulkner This can be closed, correct?

**Pull request closed without merging**
